// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {models} from '../models';

export function CancelModelDownload(arg1:string):Promise<void>;

export function DeleteModel(arg1:string):Promise<void>;

export function DownloadModel(arg1:string):Promise<void>;

export function GetAppConfig():Promise<config.AppConfig>;

export function GetSelectedModelPath():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListModels():Promise<Array<models.Info>>;

export function SelectModel(arg1:string):Promise<void>;

export function UpdateAppConfig(arg1:boolean,arg2:string):Promise<config.AppConfig>;
