// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddVideoExportFrame(arg1, arg2) {
  return window['go']['main']['App']['AddVideoExportFrame'](arg1, arg2);
}

export function CancelCaptionGeneration() {
  return window['go']['main']['App']['CancelCaptionGeneration']();
}

export function CancelModelDownload(arg1) {
  return window['go']['main']['App']['CancelModelDownload'](arg1);
}

export function CancelVideoExport() {
  return window['go']['main']['App']['CancelVideoExport']();
}

export function DeleteModel(arg1) {
  return window['go']['main']['App']['DeleteModel'](arg1);
}

export function DownloadModel(arg1) {
  return window['go']['main']['App']['DownloadModel'](arg1);
}

export function FinishVideoExport() {
  return window['go']['main']['App']['FinishVideoExport']();
}

export function GenerateCaptions(arg1, arg2) {
  return window['go']['main']['App']['GenerateCaptions'](arg1, arg2);
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetSelectedModelPath() {
  return window['go']['main']['App']['GetSelectedModelPath']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function RegisterVideoFile(arg1) {
  return window['go']['main']['App']['RegisterVideoFile'](arg1);
}

export function SelectModel(arg1) {
  return window['go']['main']['App']['SelectModel'](arg1);
}

export function SelectVideoFile() {
  return window['go']['main']['App']['SelectVideoFile']();
}

export function StartVideoExport(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartVideoExport'](arg1, arg2, arg3, arg4);
}

export function StartVideoExportWithFormat(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartVideoExportWithFormat'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateAppConfig(arg1, arg2) {
  return window['go']['main']['App']['UpdateAppConfig'](arg1, arg2);
}

export function UpdateTranscriptionDevice(arg1) {
  return window['go']['main']['App']['UpdateTranscriptionDevice'](arg1);
}
