// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetAppConfig():Promise<config.AppConfig>;

export function Greet(arg1:string):Promise<string>;

export function UpdateAppConfig(arg1:boolean,arg2:boolean,arg3:string):Promise<config.AppConfig>;
