// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelModelDownload(arg1) {
  return window['go']['main']['App']['CancelModelDownload'](arg1);
}

export function DeleteModel(arg1) {
  return window['go']['main']['App']['DeleteModel'](arg1);
}

export function DownloadModel(arg1) {
  return window['go']['main']['App']['DownloadModel'](arg1);
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetSelectedModelPath() {
  return window['go']['main']['App']['GetSelectedModelPath']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function SelectModel(arg1) {
  return window['go']['main']['App']['SelectModel'](arg1);
}

export function UpdateAppConfig(arg1, arg2) {
  return window['go']['main']['App']['UpdateAppConfig'](arg1, arg2);
}
