// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {transcription} from '../models';
import {config} from '../models';
import {models} from '../models';

export function CancelCaptionGeneration():Promise<void>;

export function CancelModelDownload(arg1:string):Promise<void>;

export function DeleteModel(arg1:string):Promise<void>;

export function DownloadModel(arg1:string):Promise<void>;

export function GenerateCaptions(arg1:string,arg2:string):Promise<transcription.Result>;

export function GetAppConfig():Promise<config.AppConfig>;

export function GetSelectedModelPath():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListModels():Promise<Array<models.Info>>;

export function RegisterVideoFile(arg1:string):Promise<Record<string, string>>;

export function SelectModel(arg1:string):Promise<void>;

export function SelectVideoFile():Promise<Record<string, string>>;

export function UpdateAppConfig(arg1:boolean,arg2:string):Promise<config.AppConfig>;
